[files]
extend-exclude = [
    ".git/",
    "resources/languages/"
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "wordpress-"
]

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
"wordpress" = "WordPress"