# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Requirements"
  link: "/requirements"
- label: "Setup new project"
  link: "/setup"
- label: "Getting started"
  link: "/getting-started"
- label: Getting started
  items:
    - label: "The Analysis Phase"
      link: "/getting-started/analysis-phase"
    - label: "Set up"
      link: "/getting-started/set-up"
    - label: "Basic styling"
      link: "/basics/basic-styling"
    - label: "Basic javascript"
      link: "/basics/basic-javascript"
- label: Basics
  items:
    - label: "Customizer settings"
      link: "/basics/customizer"
    - label: "Logo's"
      link: "/basics/logos"
    - label: "Favicons and manifest"
      link: "/basics/favicons-manifest"
    - label: "Basic styling"
      link: "/basics/basic-styling"
    - label: "Basic javascript"
      link: "/basics/basic-javascript"
    - label: "Fonts"
      link: "/basics/fonts"
- label: Blocks
  items:
    - label: "Key concepts"
      link: "/blocks/key-concepts"
    - label: "Create block"
      link: "/blocks/create-block"
    - label: "Declaration (json)"
      link: "/blocks/block-declaration"
    - label: "Controller (php)"
      link: "/blocks/block-controller"
    - label: "View (twig)"
      link: "/blocks/block-view"
    - label: "Innerblocks"
      link: "/blocks/innerblocks"
    - label: "Disabling blocks"
      link: "/blocks/disabling-blocks"
- label: Working with posts
  items:
    - label: "Post type registration (model)"
      link: "/working-with-posts/post-type-registration"
    - label: "Extending Post objects (controller)"
      link: "/working-with-posts/extending-post-objects"
    - label: "Using Post objects (view)"
      link: "/working-with-posts/using-post-objects"
- label: Extend
  items:
    - label: "Global context"
      link: "/extend/add-context"
    - label: "ACF fields"
      link: "/extend/acf-fields"
    - label: "Filters & Actions"
      link: "/extend/hooks"
    - label: "Icon picker"
      link: "/extend/icon-picker"
    - label: "Special pages"
      link: "/extend/special-pages"
    - label: "Customizer fields"
      link: "/extend/customizer-fields"
    - label: "Cards"
      link: "/extend/cards"

- label: Overwrite
  items:
    - label: "Overwrite twig files"
      link: "/overwrite/twig-files"
    - label: "Overwrite styles"
      link: "/overwrite/styles"
- label: Functions & hooks
  items:
    - label: "Helper functions"
      link: "/reference/api-functions"
    - label: "Query functions"
      link: "/reference/query-functions"
    - label: "Filter Hooks"
      link: "/reference/hooks/filters"
    - label: "Action Hooks"
      link: "/reference/hooks/actions"

- label: Classes
  items:
    - label: "Generic Ajax Query"
      link: "/reference/classes/generic-ajax-query"
    - label: "wp-lemon Site"
      link: "/reference/classes/wp-lemon-site"
    - label: "Lemon Post object"
      link: "/reference/classes/lemon-post"
- label: Deployment
  items:
    - label: "Initial deploy"
      link: "/deployment/initial-deploy"
    - label: "Deploying updates"
      link: "/deployment/updates"
- label: Migration guides
  items:
     - label: Migrate from 4 to 5
       link: /migrations/4-5
     - label: Migrate from 3 to 4
       link: /migrations/3-4
     - label: Migrate from 2 to 3
       link: /migrations/2-3
- label: More
  items:
    - label: Changelog
      link: /changelog
    - label: Presskit
      link: /presskit
- label: Learn more
  items:
    - label: "Timber"
      link: "https://timber.github.io/docs/"
    - label: "ACF Builder"
      link: "https://github.com/StoutLogic/acf-builder/wiki/"
    - label: "Bedrock"
      link: "https://github.com/roots/bedrock"
    - label: "Bootstrap"
      link: "https://getbootstrap.com/docs/5.3/getting-started/introduction/"
- label: Docs software
  items:
    - label: "GitHub"
      link: "https://github.com/rocketseat/gatsby-themes"
